# Generated by Django 4.2.2 on 2023-06-19 21:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=16)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Condidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condidate_name', models.CharField(max_length=25)),
                ('condidate_gender', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], default='gender', max_length=5)),
                ('condidate_height', models.FloatField()),
                ('condidate_age', models.IntegerField()),
                ('condidate_weight', models.FloatField()),
                ('condidate_address', models.CharField(choices=[("qoraqalpog'iston", "qoraqalpog'iston"), ('andijon', 'andijon'), ('buxoro', 'buxoro'), ("farg'ona", "farg'ona"), ('jizzah', 'jizzah'), ('namangan', 'namangan'), ('navoiy', 'navoiy'), ('qashqadaryo', 'qashqadaryo'), ('samarqand', 'samarqand'), ('sirdaryo', 'sirdaryo'), ('surxondaryo', 'surxondaryo'), ('toshkent', 'toshkent'), ('xorazm', 'xorazm'), ('boshqa_respublika', 'boshqa_respublika')], default="qoraqalpog'iston", max_length=25)),
                ('condidate_married', models.CharField(max_length=25)),
                ('condidate_profession', models.CharField(max_length=25)),
                ('condidate_nation', models.CharField(max_length=25)),
                ('condidate_health', models.CharField(max_length=50)),
                ('condidate_prayed', models.CharField(max_length=50)),
                ('condidate_desires', models.TextField()),
                ('condidate_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
