# Generated by Django 4.2.2 on 2023-06-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condidate',
            name='condidate_address',
            field=models.CharField(choices=[('AND', "Farg'ona"), ('BUX', "Farg'ona"), ('FAR', "Farg'ona"), ('NAM', "Farg'ona"), ('NAV', "Farg'ona"), ('QASH', "Farg'ona"), ('SAM', "Farg'ona"), ('SIR', "Farg'ona"), ('SRX', "Farg'ona"), ('TOSH', "Farg'ona"), ('XOR', "Farg'ona"), ('QSTN', "Farg'ona"), ('ORES', "Farg'ona")], max_length=4),
        ),
        migrations.AlterField(
            model_name='condidate',
            name='condidate_gender',
            field=models.CharField(choices=[('MAN', 'Man'), ('WMAN', 'Woman')], max_length=5),
        ),
    ]
