# Generated by Django 4.2.2 on 2023-06-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_condidate_condidate_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Condidate',
        ),
    ]
