# Generated by Django 4.2.2 on 2023-06-21 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condidate_name', models.CharField(max_length=25)),
                ('condidate_gender', models.CharField(choices=[('MAN', 'Erkak'), ('WMAN', 'Ayol')], max_length=5)),
                ('condidate_height', models.FloatField()),
                ('condidate_age', models.IntegerField()),
                ('condidate_weight', models.FloatField()),
                ('condidate_address', models.CharField(choices=[('AND', 'Andijon'), ('BUX', 'Buxoro'), ('FAR', "Farg'ona"), ('NAM', 'Namangan'), ('NAV', 'Navoiy'), ('QASH', 'Qashadaryo'), ('SAM', 'Samarqand'), ('SIR', 'Sirdaryo'), ('SRX', 'Surxondaryo'), ('JIZ', 'Jizzax'), ('TOSH', 'Toshkent'), ('XOR', 'Xorazim'), ('QSTN', "Qoraqalpog'iston"), ('ORES', 'Boshqa Respublika')], max_length=4)),
                ('condidate_married', models.CharField(max_length=25)),
                ('condidate_profession', models.CharField(max_length=25)),
                ('condidate_nation', models.CharField(max_length=25)),
                ('condidate_health', models.CharField(max_length=50)),
                ('condidate_prayed', models.CharField(max_length=50)),
                ('condidate_desires', models.TextField()),
                ('condidate_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
